version: "3"

services:
  python:
    container_name: bert_features_api
    build: ./
    restart: always
    stdin_open: true
    ports:
      - 80:5000

#    entrypoint: /usr/bin/env bash
#    command: setup.sh
