version: "3"

services:
  flask:
    container_name: bert_features_api
    build: ./
    restart: always
    stdin_open: true
    expose:
      - 5000

  nginx:
    build: nginx
    tty: true
    stdin_open: true
    restart: always
    links:
    - flask
    ports:
    - 80:9000
    volumes:
    - ./nginx:/etc/nginx